apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
  namespace: monitoring
spec:
  secretName: grafana-tls
  dnsNames:
    - grafana.myapp.localdev.me
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer