apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
namespace: prod
resources:
  - ../../base
  - prod-cert.yaml
patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml
  - path: patch-service-monitor.yaml
    target:
      kind: ServiceMonitor
      name: sample-app
images:
  - name: ghcr.io/swamyvaditya/sample-gitops-repo/sample-app
    newTag: v1.1.5
transformers:
  - env-label-transformer.yaml
