apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-

namespace: prod

resources:
  - ../../base

images:
  - name: ghcr.io/swamyvaditya/sample-app
    newTag: <to-be-overwritten-by-CI>

commonLabels:
  env: prod
