apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
namespace: prod
resources:
  - ../../base

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml
images:
  - name: ghcr.io/swamyvaditya/sample-gitops-repo/sample-app
    newTag: bbc5de9
