namePrefix: prod-
namespace: prod
resources:
  - ../../base
patches:
  - path: patch-deployment.yaml
images:
  - name: ghcr.io/swamyvaditya/sample-gitops-repo/sample-app
    newTag: c482353
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
