apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # External URL for links in UI/CLI (points to Ingress below)
  url: http://argo.localdev.me

  # Reduce token/session lifetime (good baseline for labs)
  users.session.duration: "8h"
  users.session.enabled: "true"

  # Make diffing/pruning a bit stricter and faster
  application.instanceLabelKey: argocd.argoproj.io/instance
  resource.compareoptions: |
    ignoreAggregatedRoles: true

  # (Optional) Disable anonymous access (default is already disabled)
  admin.enabled: "true"
  # ⚠️ When you add SSO later and verify admin SSO access works,
  # you can switch to:
  # admin.enabled: "false"

  # (Optional) Example OIDC skeleton for later:
  # oidc.config: |
  #   name: GitHub
  #   issuer: https://github.com/login/oauth
  #   clientID: $oidc.github.clientID
  #   clientSecret: $oidc.github.clientSecret
  #   requestedScopes: ["openid","profile","email"]
  
  # (Optional) Example Dex skeleton for later:
  #dex.config: |
  #  connectors:
  #    # GitHub example
  #    - type: github
  #      id: github
  #      name: GitHub
  #      config:
  #        clientID: $oidc.github.clientID
  #        clientSecret: $oidc.github.clientSecret
          
  # add an additional local user with apiKey and login capabilities
  #   apiKey - allows generating API keys
  #   login - allows to login using UI
  accounts.swamy: apiKey, login
  # disables user. User is enabled by default
  # accounts.swamy.enabled: "false"
