apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - argocd-cm.yaml
  - argocd-rbac-cm.yaml
  - argocd-secret.yaml
  - ingress.yaml
  - networkpolicy.yaml
