# argocd/infra.yaml
# RECOMMENDED: Create a Bootstrap App for Infrastructure components
# This App deploys the monitoring stack (Prometheus + Grafana) using Kustomize
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/swamyvaditya/sample-gitops-repo
    targetRevision: HEAD
    path: k8s/monitoring
  destination:
    server: https://host.docker.internal:6444
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true