apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.46.0
    helm:
      releaseName: loki
      values: |
        deploymentMode: SingleBinary

        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0

        memcached:
          chunks:
            enabled: true 
            resources:
              limits:
                cpu: 200m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi
        memcached:
          results:
            enabled: true 
            resources:
              limits:
                cpu: 200m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi

        loki:

          

                    
          storage:
            type: filesystem
          commonConfig:
            replication_factor: 1
          schemaConfig:
            configs:
              - from: "2024-01-01"
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h



        promtail:
          enabled: true

        grafana:
          enabled: false

        serviceMonitor:
          enabled: true

  destination:
    server: https://host.docker.internal:6444
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  
  ignoreDifferences:
  - kind: StatefulSet
    name: loki-chunks-cache
    namespace: monitoring
    jsonPointers:
    - /spec/template/spec/containers/0/resources