# argocd/loki-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.46.0
    helm:
      releaseName: loki
      values: |
        # Use filesystem (no S3)
        loki:
          storage:
            type: filesystem
          commonConfig:
            replication_factor: 1
          schemaConfig:
            configs:
              - from: "2024-01-01"
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h

        # Enable Promtail
        promtail:
          enabled: true

        # Disable Grafana sidecar
        grafana:
          enabled: false

        # Enable ServiceMonitor
        serviceMonitor:
          enabled: true

  destination:
    server: https://host.docker.internal:6444
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true