# k8s/applications/monitoring.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/swamyvaditya/sample-gitops-repo
    targetRevision: HEAD
    path: k8s/monitoring
    kustomize:
      commonAnnotations:
        argocd.argoproj.io/helm-values-file: values.yaml
  destination:
    server: https://host.docker.internal:6444
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true