apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/swamyvaditya/sample-gitops-repo.git
    targetRevision: HEAD
    path: k8s/overlays/dev
  destination:
    server: https://host.docker.internal:6444
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
