apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-secure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SwamyVaditya/sample-gitops-repo.git
    targetRevision: main         # or your chosen branch for infra
    path: k8s/overlays/secure
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - ApplyOutOfSyncOnly=true
