name: CD Promotion Pipeline

on:
  push:
    branches:
      - staging
      - main

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set environment based on branch
        id: env
        run: |
          if [[ "${GITHUB_REF##*/}" == "staging" ]]; then
            echo "env=staging" >> "$GITHUB_OUTPUT"
          elif [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "env=prod" >> "$GITHUB_OUTPUT"
          fi

      - name: Patch overlay with SHA
        env:
          SHA: ${{ github.sha }}
        run: |
          OVERLAY="k8s/overlays/${{ steps.env.outputs.env }}/patch-deployment.yaml"
          sed -i "s|image: .*$|image: ghcr.io/${{ github.repository }}/sample-app:$SHA|" "$OVERLAY"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add "$OVERLAY"
          git commit -m "Promote to ${{ steps.env.outputs.env }}: $SHA"
          git push origin HEAD:${{ github.ref_name }}
