name: CI/CD Pipeline

on:
  push:
    branches: [main]
    paths:
      - 'sample-app/**'            # Trigger only when app code changes
      - 'k8s/**'
      - '.github/workflows/update-and-deploy.yaml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  #IMAGE_NAME: ${{ github.repository }}/sample-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      deployments: write

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set lowercase IMAGE_NAME
      id: set_image_name
      run: |
        image_name="${GITHUB_REPOSITORY}/sample-app"
        echo "image_name_lc=${image_name,,}" >> $GITHUB_OUTPUT

    - name: Extract Git commit SHA
      id: vars
      run: echo "TAG=sha-${GITHUB_SHA::7}" >> $GITHUB_ENV
    
    - name: Extract short SHA
      id: short_sha
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./sample-app
        push: true
        tags: ${{ env.REGISTRY }}/${{ steps.set_image_name.outputs.image_name_lc }}:${{ env.TAG }}

    - name: Update image tag in kustomization (dev for now)
      run: |
        sed -i "s|image: .*$|image: ghcr.io/${{ steps.set_image_name.outputs.image_name_lc }}:${{ env.sha_short }}|" k8s/overlays/dev/patch-deployment.yaml

    - name: Commit and push updated kustomization
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add overlays/dev/patch-deployment.yaml
        git commit -m "Update dev image tag to ${{ env.TAG }}"
        git push
