apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: sample-app
          image: ghcr.io/swamyvaditya/sample-gitops-repo/sample-app:latest
